require_relative 'hwloc/Hwloc.rb'
require_relative 'hwloc/Bitmap.rb'
require_relative 'hwloc/Obj.rb'
require_relative 'hwloc/Topology.rb'
require_relative 'hwloc/Bind.rb'
require_relative 'hwloc/Edition.rb'
require_relative 'hwloc/Export.rb'
